### ISSUE TITLE
suggestion - MetaMask compatibility

### ISSUE THREAD

**Issue by jmiehau** [flyswatter/Dapper#1]
We still doesn't have a light client for Mist and it makes really difficult to interact with the Mainnet or Morden, this project could be very interesting to have an alternative way to the "Watch contract" feature on Mist. 

Then Injected Web3 to interact with Ethereum through Metamask could be awesome.

**Comment by danfinlay** [comment]
Oh don't worry, MetaMask compatibility would be one of the first things on the list here. It's the environment I'd be developing in.
